#!/usr/bin/env python3
"""Regenerate creature-swarm/TASKS.md from the state of the working tree.

A task is checked off when every one of its declared output files exists.
This is a deterministic proxy for "done" — the real bar is green tests
(the plan is TDD), but file presence is what we can check cheaply on every
commit. Source of truth for task detail:
docs/superpowers/plans/2026-07-17-creature-swarm.md

Run automatically by .githooks/pre-commit; safe to run by hand any time.
"""
from __future__ import annotations

import os
import subprocess
import sys

# (id, title, [output files relative to repo root])
TASKS = [
    ("1", "Scaffold folder, requirements, and shared managed-agents client",
     ["creature-swarm/requirements.txt", "creature-swarm/.env.example",
      "creature-swarm/lib/client.py"]),
    ("2", "Creature Spec loader + validator",
     ["creature-swarm/lib/spec.py", "creature-swarm/tests/test_spec.py"]),
    ("3", "Procedural 3D builder (trimesh -> glb)",
     ["creature-swarm/skills/procedural-creature-3d/build.py",
      "creature-swarm/tests/test_creature3d.py"]),
    ("4", "Field-guide HTML renderer + template",
     ["creature-swarm/skills/fieldguide-html/template.html",
      "creature-swarm/skills/fieldguide-html/render.py",
      "creature-swarm/tests/test_fieldguide.py"]),
    ("5", "Author the specialist skills (SKILL.md files)",
     ["creature-swarm/skills/creature-biology/SKILL.md",
      "creature-swarm/skills/habitat-ecology/SKILL.md",
      "creature-swarm/skills/folklore-society/SKILL.md"]),
    ("6", "Agent definitions (system prompts + roster config)",
     ["creature-swarm/agents/definitions.py"]),
    ("7", "setup_environment.py",
     ["creature-swarm/setup_environment.py"]),
    ("8", "create_specialists.py",
     ["creature-swarm/create_specialists.py"]),
    ("9", "upload_skills.py (with the object-vs-dict fix)",
     ["creature-swarm/upload_skills.py"]),
    ("10", "create_coordinator.py",
     ["creature-swarm/create_coordinator.py"]),
    ("11", "run_creature_swarm.py",
     ["creature-swarm/run_creature_swarm.py"]),
    ("12", "download_deliverable.py",
     ["creature-swarm/download_deliverable.py"]),
    ("13", "Synthetic doodle, README, full-suite + live-run verification",
     ["creature-swarm/synthetic-data/doodle-example.png",
      "creature-swarm/README.md"]),
]

# Already merged via a separate PR — a read-only input, shown for context.
PREREQ = [
    ("Creature Spec contract",
     ["creature-swarm/contracts/creature-spec.schema.json",
      "creature-swarm/contracts/creature-spec.example.json"]),
]

# Stretch goal — ships as a stub in V1, tracked but not counted in the 13.
STRETCH = [
    ("S", "Walk-cycle animator (stub -> full)",
     ["creature-swarm/skills/walk-cycle-anim/SKILL.md"]),
]

OUTPUT = "creature-swarm/TASKS.md"


def repo_root() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip()


def done(root: str, files: list[str]) -> bool:
    return all(os.path.exists(os.path.join(root, f)) for f in files)


def box(is_done: bool) -> str:
    return "[x]" if is_done else "[ ]"


def render(root: str) -> str:
    complete = sum(1 for _, _, files in TASKS if done(root, files))
    total = len(TASKS)
    lines = [
        "# Creature Swarm — Task Checklist",
        "",
        "> Auto-generated by `.githooks/pre-commit` on every commit. A task is",
        "> checked off when all of its output files exist in the repo. **Do not",
        "> hand-edit the checkboxes** — they are regenerated and re-staged each",
        "> commit. Full task detail lives in",
        "> `docs/superpowers/plans/2026-07-17-creature-swarm.md`.",
        "",
        f"**Progress: {complete}/{total} tasks complete.**",
        "",
        "## Prerequisite (merged separately)",
        "",
    ]
    for title, files in PREREQ:
        lines.append(f"- {box(done(root, files))} {title} "
                     f"(`{files[0]}`)")
    lines += ["", "## V1 tasks", ""]
    for tid, title, files in TASKS:
        filelist = ", ".join(f"`{f}`" for f in files)
        lines.append(f"- {box(done(root, files))} **Task {tid}** — {title}")
        lines.append(f"  <br/>outputs: {filelist}")
    lines += ["", "## Stretch", ""]
    for _tid, title, files in STRETCH:
        filelist = ", ".join(f"`{f}`" for f in files)
        lines.append(f"- {box(done(root, files))} {title}")
        lines.append(f"  <br/>outputs: {filelist}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    root = repo_root()
    content = render(root)
    path = os.path.join(root, OUTPUT)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
